#!/usr/bin/env node
'use strict';
/**
 * Zero-dependency static build for sophiegarden.
 * Renders src/pages/*.html through src/partials/layout.html (which itself
 * includes nav/mobile-menu/footer/sd-banner/icons partials), substituting
 * {{var}} placeholders and {{> partial}} includes, into sophiegarden/dist/.
 *
 * Template syntax (intentionally minimal — see README.md):
 *   {{a.b.c}}          value lookup in the vars object passed to render()
 *   {{> partials/x}}   include partials/x.html, rendered with the same vars
 *   {{#if flag}}...{{/if}}   keep the block only if vars.flag is truthy
 *
 * Never hand-edit files in dist/ — they are generated by this script.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = __dirname;
const DIST = path.join(ROOT, 'dist');

const business = JSON.parse(fs.readFileSync(path.join(SRC, 'data', 'business.json'), 'utf8'));
const pages = JSON.parse(fs.readFileSync(path.join(SRC, 'data', 'pages.json'), 'utf8'));

function readPartial(relPath) {
  const file = path.join(SRC, 'partials', relPath.endsWith('.html') ? relPath : `${relPath}.html`);
  return fs.readFileSync(file, 'utf8');
}

function lookup(vars, keyPath) {
  const value = keyPath.split('.').reduce((acc, key) => (acc == null ? acc : acc[key]), vars);
  return value == null ? undefined : value;
}

// Renders {{#if flag}}...{{/if}} blocks first (so partial includes inside a
// hidden block never even get processed), then {{> partial}} includes
// (recursively), then {{var}} substitutions. Throws if a flag/partial/var is
// referenced but not present in vars, so a typo fails the build loudly
// instead of shipping a literal "{{...}}" to production.
function render(template, vars) {
  let out = template.replace(/{{#if\s+([\w.]+)}}([\s\S]*?){{\/if}}/g, (match, flag, inner) => {
    if (!(flag in vars) && lookup(vars, flag) === undefined) {
      throw new Error(`Unknown {{#if}} flag: "${flag}"`);
    }
    return lookup(vars, flag) ? inner : '';
  });

  out = out.replace(/{{>\s*([\w./-]+)\s*}}/g, (match, partialName) => {
    const partialSrc = readPartial(partialName);
    return render(partialSrc, vars);
  });

  out = out.replace(/{{\s*([\w.]+)\s*}}/g, (match, keyPath) => {
    const value = lookup(vars, keyPath);
    if (value === undefined) {
      throw new Error(`Unknown template variable: "${keyPath}"`);
    }
    return String(value);
  });

  return out;
}

function attrsFor(navKey, activeKey) {
  return navKey === activeKey ? ' class="active" aria-current="page"' : '';
}

function copyStaticAssets() {
  const assets = ['style.css', 'main.js', 'logo.png', 'steellogo.png', 'robots.txt', 'sitemap.xml', 'fb-posts.json'];
  for (const name of assets) {
    const from = path.join(ROOT, name);
    if (fs.existsSync(from)) fs.copyFileSync(from, path.join(DIST, name));
  }

  // Hero slider photos and any other imagery live in src/images/ (a static
  // asset folder, not a template) and are copied through to dist/images/.
  const imagesSrc = path.join(SRC, 'images');
  if (fs.existsSync(imagesSrc)) {
    fs.cpSync(imagesSrc, path.join(DIST, 'images'), { recursive: true });
  }
}

function buildPage(key, cfg) {
  const pageSrcPath = path.join(SRC, 'pages', cfg.file);
  const raw = fs.readFileSync(pageSrcPath, 'utf8');

  // src/pages/<page>.html holds three sections separated by an
  // "<!--STYLE-->" / "<!--MAIN-->" / "<!--SCHEMA-->" / "<!--SCRIPT-->" marker
  // convention (see README.md) so the build can slot each into layout.html.
  const sections = { schema: '', style: '', main: '', script: '' };
  const markerRe = /<!--(SCHEMA|STYLE|MAIN|SCRIPT)-->\r?\n([\s\S]*?)(?=<!--(?:SCHEMA|STYLE|MAIN|SCRIPT)-->|$)/g;
  let m;
  while ((m = markerRe.exec(raw))) {
    sections[m[1].toLowerCase()] = m[2].replace(/\s+$/, '');
  }

  // Base vars (everything except page.schema/style/main/extraScript) — used
  // to pre-render each page section on its own first. This matters because
  // String.replace never rescans replacement text: if we substituted the raw
  // (unrendered) section strings directly into the layout in a single pass,
  // any {{biz.*}} reference written inside a page's own content would survive
  // as a literal "{{...}}" in the final output instead of being resolved.
  const baseVars = {
    biz: business,
    showFeatSlot: !!cfg.showFeatSlot,
    showSdBanner: !!cfg.showSdBanner,
    isDefaultFooterThird: cfg.footerThirdColumn !== 'partners',
    isPartnersFooterThird: cfg.footerThirdColumn === 'partners',
    navKinaletAttrs: attrsFor('kinalet', cfg.activeNav),
    navHirekAttrs: attrsFor('hirek', cfg.activeNav),
    navRolunkAttrs: attrsFor('rolunk', cfg.activeNav),
    navKapcsolatAttrs: attrsFor('kapcsolat', cfg.activeNav),
    navLogoAttrs: cfg.activeNav === 'home' ? ' aria-current="page"' : '',
    mobileKinaletAttrs: attrsFor('kinalet', cfg.activeNav).replace(' aria-current="page"', ''),
    mobileHirekAttrs: attrsFor('hirek', cfg.activeNav).replace(' aria-current="page"', ''),
    mobileRolunkAttrs: attrsFor('rolunk', cfg.activeNav).replace(' aria-current="page"', ''),
    mobileKapcsolatAttrs: attrsFor('kapcsolat', cfg.activeNav).replace(' aria-current="page"', ''),
  };

  const vars = {
    ...baseVars,
    page: {
      title: cfg.title,
      description: cfg.description,
      keywords: cfg.keywords,
      canonical: cfg.canonical,
      ogTitle: cfg.ogTitle,
      ogDescription: cfg.ogDescription,
      robots: cfg.robots || 'index, follow, max-snippet:-1, max-image-preview:large',
      bodyClassAttr: cfg.bodyClass ? ` class="${cfg.bodyClass}"` : '',
      schema: render(sections.schema, baseVars),
      style: render(sections.style, baseVars),
      main: render(sections.main, baseVars),
      extraScript: render(sections.script, baseVars),
    },
  };

  const layoutSrc = readPartial('layout');
  const html = render(layoutSrc, vars);

  if (html.includes('{{')) {
    const stray = html.match(/\{\{[^}]*\}\}/);
    throw new Error(`Build for "${key}" left an unresolved placeholder: ${stray && stray[0]}`);
  }

  fs.writeFileSync(path.join(DIST, cfg.file), html);
}

function main() {
  fs.mkdirSync(DIST, { recursive: true });

  const meta = JSON.parse(fs.readFileSync(path.join(SRC, 'data', 'page-meta.json'), 'utf8'));

  for (const [key, cfg] of Object.entries(pages)) {
    buildPage(key, { ...cfg, ...meta[key] });
  }

  copyStaticAssets();
  console.log(`Built ${Object.keys(pages).length} pages into ${path.relative(ROOT, DIST)}/`);
}

main();
